spring:
  application:
    name: first-project
  ai:
    google:
      genai:
        api-key: ${GENAI_API_KEY}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI}
          audience: ${OAUTH2_AUDIENCE}
